{"name": "Successful login", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_TIMED_OUT\n  (Session info: chrome=134.0.6998.89)\nStacktrace:\n\tGetHandleVerifier [0x00CCB5A3+24387]\n\t(No symbol) [0x00C55904]\n\t(No symbol) [0x00B30753]\n\t(No symbol) [0x00B2DB9E]\n\t(No symbol) [0x00B214B8]\n\t(No symbol) [0x00B22DC0]\n\t(No symbol) [0x00B21747]\n\t(No symbol) [0x00B212A3]\n\t(No symbol) [0x00B20FB1]\n\t(No symbol) [0x00B1EE80]\n\t(No symbol) [0x00B1F91B]\n\t(No symbol) [0x00B3420E]\n\t(No symbol) [0x00BBFDE7]\n\t(No symbol) [0x00B9D84C]\n\t(No symbol) [0x00BBF138]\n\t(No symbol) [0x00B9D646]\n\t(No symbol) [0x00B6C59F]\n\t(No symbol) [0x00B6D8E4]\n\tGetHandleVerifier [0x00FCD883+3179043]\n\tGetHandleVerifier [0x00FE6CF9+3282585]\n\tGetHandleVerifier [0x00FE167C+3260444]\n\tGetHandleVerifier [0x00D64330+650448]\n\t(No symbol) [0x00C5ED0D]\n\t(No symbol) [0x00C5BAF8]\n\t(No symbol) [0x00C5BC99]\n\t(No symbol) [0x00C4E530]\n\tBaseThreadInitThunk [0x766A5D49+25]\n\tRtlInitializeExceptionChain [0x7753CE3B+107]\n\tRtlGetAppContainerNamedObjectPath [0x7753CDC1+561]\n\n", "trace": "  File \"C:\\Users\\Mike Redondo\\OneDrive\\Desktop\\asdasdas\\.venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Mike Redondo\\OneDrive\\Desktop\\asdasdas\\.venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\example_steps.py\", line 8, in step_open_browser\n    context.driver.get(\"https://practicetestautomation.com/practice-test-login/\")\n  File \"C:\\Users\\Mike Redondo\\OneDrive\\Desktop\\asdasdas\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 454, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Users\\Mike Redondo\\OneDrive\\Desktop\\asdasdas\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Mike Redondo\\OneDrive\\Desktop\\asdasdas\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given I open the browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_TIMED_OUT\n  (Session info: chrome=134.0.6998.89)\nStacktrace:\n\tGetHandleVerifier [0x00CCB5A3+24387]\n\t(No symbol) [0x00C55904]\n\t(No symbol) [0x00B30753]\n\t(No symbol) [0x00B2DB9E]\n\t(No symbol) [0x00B214B8]\n\t(No symbol) [0x00B22DC0]\n\t(No symbol) [0x00B21747]\n\t(No symbol) [0x00B212A3]\n\t(No symbol) [0x00B20FB1]\n\t(No symbol) [0x00B1EE80]\n\t(No symbol) [0x00B1F91B]\n\t(No symbol) [0x00B3420E]\n\t(No symbol) [0x00BBFDE7]\n\t(No symbol) [0x00B9D84C]\n\t(No symbol) [0x00BBF138]\n\t(No symbol) [0x00B9D646]\n\t(No symbol) [0x00B6C59F]\n\t(No symbol) [0x00B6D8E4]\n\tGetHandleVerifier [0x00FCD883+3179043]\n\tGetHandleVerifier [0x00FE6CF9+3282585]\n\tGetHandleVerifier [0x00FE167C+3260444]\n\tGetHandleVerifier [0x00D64330+650448]\n\t(No symbol) [0x00C5ED0D]\n\t(No symbol) [0x00C5BAF8]\n\t(No symbol) [0x00C5BC99]\n\t(No symbol) [0x00C4E530]\n\tBaseThreadInitThunk [0x766A5D49+25]\n\tRtlInitializeExceptionChain [0x7753CE3B+107]\n\tRtlGetAppContainerNamedObjectPath [0x7753CDC1+561]\n\n", "trace": "  File \"C:\\Users\\Mike Redondo\\OneDrive\\Desktop\\asdasdas\\.venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Mike Redondo\\OneDrive\\Desktop\\asdasdas\\.venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\example_steps.py\", line 8, in step_open_browser\n    context.driver.get(\"https://practicetestautomation.com/practice-test-login/\")\n  File \"C:\\Users\\Mike Redondo\\OneDrive\\Desktop\\asdasdas\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 454, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Users\\Mike Redondo\\OneDrive\\Desktop\\asdasdas\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Mike Redondo\\OneDrive\\Desktop\\asdasdas\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1742206504009, "stop": 1742206546373}, {"name": "When I enter the username \"student\"", "status": "skipped", "start": 1742206546375, "stop": 1742206546375}, {"name": "And I enter the password \"Password123\"", "status": "skipped", "start": 1742206546375, "stop": 1742206546375}, {"name": "And I click the login button", "status": "skipped", "start": 1742206546375, "stop": 1742206546375}, {"name": "Then I should see the success message \"Logged In Successfully\"", "status": "skipped", "start": 1742206546375, "stop": 1742206546375}], "start": 1742206503996, "stop": 1742206546375, "uuid": "eb1621d2-72bc-493f-b7c1-b56fbcb67929", "historyId": "726be7e7527fec01ad1c7990abd2e6b0", "fullName": "Login and Navigate to Pages: Successful login", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Login and Navigate to Pages"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}