{"name": "Successful login", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=134.0.6998.89)\nStacktrace:\n\tGetHandleVerifier [0x00D2B5A3+24387]\n\t(No symbol) [0x00CB5904]\n\t(No symbol) [0x00B90753]\n\t(No symbol) [0x00B6F83E]\n\t(No symbol) [0x00C0454E]\n\t(No symbol) [0x00C1EA19]\n\t(No symbol) [0x00BFD646]\n\t(No symbol) [0x00BCC59F]\n\t(No symbol) [0x00BCD8E4]\n\tGetHandleVerifier [0x0102D883+3179043]\n\tGetHandleVerifier [0x01046CF9+3282585]\n\tGetHandleVerifier [0x0104167C+3260444]\n\tGetHandleVerifier [0x00DC4330+650448]\n\t(No symbol) [0x00CBED0D]\n\t(No symbol) [0x00CBBAF8]\n\t(No symbol) [0x00CBBC99]\n\t(No symbol) [0x00CAE530]\n\tBaseThreadInitThunk [0x766A5D49+25]\n\tRtlInitializeExceptionChain [0x7753CE3B+107]\n\tRtlGetAppContainerNamedObjectPath [0x7753CDC1+561]\n\n", "trace": "  File \"C:\\Users\\Mike Redondo\\OneDrive\\Desktop\\asdasdas\\.venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Mike Redondo\\OneDrive\\Desktop\\asdasdas\\.venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\example_steps.py\", line 9, in step_open_browser\n    context.driver.maximize_window()\n  File \"C:\\Users\\Mike Redondo\\OneDrive\\Desktop\\asdasdas\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 622, in maximize_window\n    self.execute(command, None)\n  File \"C:\\Users\\Mike Redondo\\OneDrive\\Desktop\\asdasdas\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Mike Redondo\\OneDrive\\Desktop\\asdasdas\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given I open the browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=134.0.6998.89)\nStacktrace:\n\tGetHandleVerifier [0x00D2B5A3+24387]\n\t(No symbol) [0x00CB5904]\n\t(No symbol) [0x00B90753]\n\t(No symbol) [0x00B6F83E]\n\t(No symbol) [0x00C0454E]\n\t(No symbol) [0x00C1EA19]\n\t(No symbol) [0x00BFD646]\n\t(No symbol) [0x00BCC59F]\n\t(No symbol) [0x00BCD8E4]\n\tGetHandleVerifier [0x0102D883+3179043]\n\tGetHandleVerifier [0x01046CF9+3282585]\n\tGetHandleVerifier [0x0104167C+3260444]\n\tGetHandleVerifier [0x00DC4330+650448]\n\t(No symbol) [0x00CBED0D]\n\t(No symbol) [0x00CBBAF8]\n\t(No symbol) [0x00CBBC99]\n\t(No symbol) [0x00CAE530]\n\tBaseThreadInitThunk [0x766A5D49+25]\n\tRtlInitializeExceptionChain [0x7753CE3B+107]\n\tRtlGetAppContainerNamedObjectPath [0x7753CDC1+561]\n\n", "trace": "  File \"C:\\Users\\Mike Redondo\\OneDrive\\Desktop\\asdasdas\\.venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Mike Redondo\\OneDrive\\Desktop\\asdasdas\\.venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\example_steps.py\", line 9, in step_open_browser\n    context.driver.maximize_window()\n  File \"C:\\Users\\Mike Redondo\\OneDrive\\Desktop\\asdasdas\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 622, in maximize_window\n    self.execute(command, None)\n  File \"C:\\Users\\Mike Redondo\\OneDrive\\Desktop\\asdasdas\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Mike Redondo\\OneDrive\\Desktop\\asdasdas\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1742202957966, "stop": 1742202996848}, {"name": "When I enter the username \"student\"", "status": "skipped", "start": 1742202996851, "stop": 1742202996851}, {"name": "And I enter the password \"Password123\"", "status": "skipped", "start": 1742202996851, "stop": 1742202996851}, {"name": "And I click the login button", "status": "skipped", "start": 1742202996851, "stop": 1742202996851}, {"name": "Then I should see the success message \"Logged In Successfully\"", "status": "skipped", "start": 1742202996851, "stop": 1742202996851}], "start": 1742202957958, "stop": 1742202996851, "uuid": "18b2ea8b-2416-42fb-917b-b0b6676b1a45", "historyId": "726be7e7527fec01ad1c7990abd2e6b0", "fullName": "Login and Navigate to Pages: Successful login", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Login and Navigate to Pages"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}