{"name": "Invalid login", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: failed to change window state to 'normal', current state is 'maximized'\n  (Session info: chrome=134.0.6998.89)\nStacktrace:\n\tGetHandleVerifier [0x00C3B5A3+24387]\n\t(No symbol) [0x00BC5904]\n\t(No symbol) [0x00AA0753]\n\t(No symbol) [0x00A836DA]\n\t(No symbol) [0x00A81043]\n\t(No symbol) [0x00A807CF]\n\t(No symbol) [0x00B42668]\n\t(No symbol) [0x00B0D84C]\n\t(No symbol) [0x00B2F138]\n\t(No symbol) [0x00B0D646]\n\t(No symbol) [0x00ADC59F]\n\t(No symbol) [0x00ADD8E4]\n\tGetHandleVerifier [0x00F3D883+3179043]\n\tGetHandleVerifier [0x00F56CF9+3282585]\n\tGetHandleVerifier [0x00F5167C+3260444]\n\tGetHandleVerifier [0x00CD4330+650448]\n\t(No symbol) [0x00BCED0D]\n\t(No symbol) [0x00BCBAF8]\n\t(No symbol) [0x00BCBC99]\n\t(No symbol) [0x00BBE530]\n\tBaseThreadInitThunk [0x766A5D49+25]\n\tRtlInitializeExceptionChain [0x7753CE3B+107]\n\tRtlGetAppContainerNamedObjectPath [0x7753CDC1+561]\n\n", "trace": "  File \"C:\\Users\\Mike Redondo\\OneDrive\\Desktop\\asdasdas\\.venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Mike Redondo\\OneDrive\\Desktop\\asdasdas\\.venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\example_steps.py\", line 9, in step_open_browser\n    context.driver.maximize_window()\n  File \"C:\\Users\\Mike Redondo\\OneDrive\\Desktop\\asdasdas\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 622, in maximize_window\n    self.execute(command, None)\n  File \"C:\\Users\\Mike Redondo\\OneDrive\\Desktop\\asdasdas\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Mike Redondo\\OneDrive\\Desktop\\asdasdas\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given I open the browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: failed to change window state to 'normal', current state is 'maximized'\n  (Session info: chrome=134.0.6998.89)\nStacktrace:\n\tGetHandleVerifier [0x00C3B5A3+24387]\n\t(No symbol) [0x00BC5904]\n\t(No symbol) [0x00AA0753]\n\t(No symbol) [0x00A836DA]\n\t(No symbol) [0x00A81043]\n\t(No symbol) [0x00A807CF]\n\t(No symbol) [0x00B42668]\n\t(No symbol) [0x00B0D84C]\n\t(No symbol) [0x00B2F138]\n\t(No symbol) [0x00B0D646]\n\t(No symbol) [0x00ADC59F]\n\t(No symbol) [0x00ADD8E4]\n\tGetHandleVerifier [0x00F3D883+3179043]\n\tGetHandleVerifier [0x00F56CF9+3282585]\n\tGetHandleVerifier [0x00F5167C+3260444]\n\tGetHandleVerifier [0x00CD4330+650448]\n\t(No symbol) [0x00BCED0D]\n\t(No symbol) [0x00BCBAF8]\n\t(No symbol) [0x00BCBC99]\n\t(No symbol) [0x00BBE530]\n\tBaseThreadInitThunk [0x766A5D49+25]\n\tRtlInitializeExceptionChain [0x7753CE3B+107]\n\tRtlGetAppContainerNamedObjectPath [0x7753CDC1+561]\n\n", "trace": "  File \"C:\\Users\\Mike Redondo\\OneDrive\\Desktop\\asdasdas\\.venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Mike Redondo\\OneDrive\\Desktop\\asdasdas\\.venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\example_steps.py\", line 9, in step_open_browser\n    context.driver.maximize_window()\n  File \"C:\\Users\\Mike Redondo\\OneDrive\\Desktop\\asdasdas\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 622, in maximize_window\n    self.execute(command, None)\n  File \"C:\\Users\\Mike Redondo\\OneDrive\\Desktop\\asdasdas\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Mike Redondo\\OneDrive\\Desktop\\asdasdas\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1742232748507, "stop": 1742232749269}, {"name": "When I enter the username \"student\"", "status": "skipped", "start": 1742232749270, "stop": 1742232749270}, {"name": "And I enter the password \"Password123\"", "status": "skipped", "start": 1742232749270, "stop": 1742232749270}, {"name": "And I click the login button", "status": "skipped", "start": 1742232749270, "stop": 1742232749270}, {"name": "Then I should see the success message \"Invalid login\"", "status": "skipped", "start": 1742232749270, "stop": 1742232749270}], "start": 1742232748504, "stop": 1742232749270, "uuid": "f687e3a5-cc64-4d82-8785-e36fe48fc918", "historyId": "35890fcf46fa3dcb90b7287fed59418a", "fullName": "Login and Navigate to Pages: Invalid login", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Login and Navigate to Pages"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}